/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author alejandro
 */
public class JFrameVerificador extends javax.swing.JFrame {

    /**
     * Creates new form Verificador
     */
    public JFrameVerificador() {
        initComponents();
        setupUI(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jLabelInstrucciones = new javax.swing.JLabel();
        jLabelGif = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jLabelProducto = new javax.swing.JLabel();
        jLabelAlerta = new javax.swing.JLabel();
        jLabelMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(28, 189, 111));
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabelLogo.setText("jLabelLogo");
        jLabelLogo.setToolTipText("");

        jLabelInstrucciones.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInstrucciones.setText("<html><body><p align=\"center\">Acerca el código de barras<br>del producto al lector para<br>consultar su precio.</p></body></html>");
        jLabelInstrucciones.setToolTipText("");

        jLabelGif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGif.setText("jLabelGif");
        jLabelGif.setToolTipText("");

        jLabelInfo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelInfo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInfo.setText("<html><body>\n\n<p align=\"center\">{producto}<br>\nPrecio: {precio}<br>\nDisponibles: {cantidad}</p>\n\n</body></html>");
        jLabelInfo.setToolTipText("");
        jLabelInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProducto.setText("jLabelProducto");
        jLabelProducto.setToolTipText("");

        jLabelAlerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAlerta.setText("jLabelAlerta");
        jLabelAlerta.setToolTipText("");

        jLabelMensaje.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelMensaje.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMensaje.setText("<html><body><p align=\"center\">No fue posible leer el código de<br>barras.<br><br>Por favor intente de nuevo o solicite<br>ayuda del personal.</p></body></html>");
        jLabelMensaje.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogo)
                    .addComponent(jLabelGif)
                    .addComponent(jLabelProducto)
                    .addComponent(jLabelInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlerta)
                    .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelGif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAlerta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !codigo.isEmpty()) 
        {
            timer.restart();
            togglePantallaInicio(false);
            CargarProducto(codigo);
            codigo = "";
        }
        else if (evt.getKeyChar() != KeyEvent.VK_ENTER) {
            codigo += evt.getKeyChar();
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVerificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVerificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVerificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVerificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameVerificador().setVisible(true);
            }
        });
    }
    
    // Timer
    int delay = 5000; //milliseconds
    
    ActionListener taskPerformer = (ActionEvent evt) -> {
        //...Perform a task...
        togglePantallaProducto(false);
        togglePantallaAlerta(false);
        togglePantallaInicio(true);
    };
    
    Timer timer = new Timer(delay, taskPerformer);
    
    // Variables
    private String codigo = "";
    
    // Funciones
    private void setupUI() {
        System.out.println("setupUI() called.");
        
        // Cambiar ventana a pantalla completa.
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize);
        
        // Cambiar el color del fondo.
        this.getContentPane().setBackground(new Color(28, 189, 111));

        // Usar JLabels como contenedores de imagenes y ajustar la posicion de los objetos en pantalla.
        this.setLayout(null);
        
        setupPantallaInicio();
        setupPantallaProducto();
        setupPantallaAlerta();
        
        togglePantallaAlerta(false);
        togglePantallaProducto(false);
    }
    
    private void setupPantallaInicio() {
        URL logo = this.getClass().getResource("superdelsur.png");
        URL gif = this.getClass().getResource("barcode-scan.gif");

        jLabelLogo.setText("<html><img src='" + logo + "' width='316' height='190'>");
        jLabelGif.setText("<html><img src='" + gif + "' width='200' height='200'>");
        jLabelLogo.setSize(316, 200);
        jLabelGif.setSize(200, 200);
        
        jLabelLogo.setLocation(
                (this.getWidth() / 2) - (jLabelLogo.getWidth() / 2), 50
        );
        jLabelInstrucciones.setLocation(
                (this.getWidth() / 2) - (jLabelInstrucciones.getWidth() / 2), 
                jLabelLogo.getY() + jLabelLogo.getHeight() + 25
        );
        jLabelGif.setLocation(
                (this.getWidth() / 2) - (jLabelGif.getWidth() / 2), 
                jLabelInstrucciones.getY() + jLabelInstrucciones.getHeight() + 50
        );
    }
    
    private void setupPantallaAlerta() {
        URL alerta = this.getClass().getResource("exclamation.png");
        
        jLabelAlerta.setText("<html><img src='" + alerta + "' width='300' height='300'>");
        jLabelAlerta.setSize(300, 300);
        
        jLabelAlerta.setLocation(
                (this.getWidth() / 2) - (jLabelAlerta.getWidth() / 2), 
                (this.getHeight() / 2) - (jLabelAlerta.getHeight() / 2) - 200
        );
        jLabelMensaje.setLocation(
                (this.getWidth() / 2) - (jLabelMensaje.getWidth() / 2), 
                jLabelAlerta.getY() + jLabelAlerta.getHeight() + 50
        );
    }
    
    private void setupPantallaProducto() {
        jLabelProducto.setVisible(false);
        jLabelInfo.setVisible(false);
        jLabelInfo.setLocation(
                (this.getWidth() / 2) - (jLabelInfo.getWidth() / 2), 
                jLabelLogo.getY() + jLabelLogo.getHeight() + 25
        );
    }
    
    private void togglePantallaInicio(boolean value) {
        jLabelInstrucciones.setVisible(value);
        jLabelGif.setVisible(value);
    }

    private void togglePantallaProducto(boolean value) {
        jLabelProducto.setVisible(value);
        jLabelInfo.setVisible(value);
    }
    
    private void togglePantallaAlerta(boolean value) {
        jLabelLogo.setVisible(!value);
        jLabelAlerta.setVisible(value);
        jLabelMensaje.setVisible(value);
    }
    
    private void CargarProducto(String codigo) 
    {
        try {
            Connection connection = null;
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/isw3", "root", "");
            Statement statement = connection.createStatement();
            
            ResultSet result = statement.executeQuery(
                    "SELECT ProductoNombre, ProductoPrecio, ProductoCantidad, ProductoImagen "
                    + "FROM productos "
                    + "WHERE ProductoCodigo = " + codigo);
            
            if (result.next())
            {
                jLabelInfo.setText("<html><body><p align='center'>" + result.getString(1)
                        + "<br>Precio: $" + result.getString(2)
                        + "<br>Disponibles: " + result.getString(3)
                        + "</p></body></html>");
                
                jLabelProducto.setText("<html><img src='" + result.getString(4) + "' width='300' height='300'>");
                jLabelProducto.setSize(300, 300);
                jLabelProducto.setLocation(
                        (this.getWidth() / 2) - (jLabelProducto.getWidth() / 2), 
                        jLabelInfo.getY() + jLabelInfo.getHeight() + 50
                );
                togglePantallaProducto(true);
                togglePantallaAlerta(false);
            }
            else {
                togglePantallaProducto(false);
                togglePantallaAlerta(true);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(JFrameVerificador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAlerta;
    private javax.swing.JLabel jLabelGif;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelInstrucciones;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelProducto;
    // End of variables declaration//GEN-END:variables
}
